- .gitignore
- build.gradle
- src/main/java/com/mergeco/olijang/config/BeanConfiguration.java
- src/main/java/com/mergeco/olijang/report/controller/ReportController.java
- src/main/java/com/mergeco/olijang/report/entity/Report.java
- src/main/java/com/mergeco/olijang/report/entity/ReportCategory.java
- src/main/java/com/mergeco/olijang/report/model/dto/ReportCategoryDTO.java
- src/main/java/com/mergeco/olijang/report/model/dto/ReportDTO.java
- src/main/java/com/mergeco/olijang/report/repository/ReportRepository.java
- src/main/java/com/mergeco/olijang/report/service/ReportService.java
- src/main/resources/application.yml
- src/test/java/com/mergeco/olijang/report/ReportTests.java
* * *
nativeQuery 테스트 중입니다.
- 결과 타입을 정의한 네이티브 사용하여 테스트 중이며, 테스트 실패로 수정중입니다.
> 신고기능 TDD진행

- .gitignore
- src/main/java/com/mergeco/olijang/inquery/controller/InqController.java
- src/main/java/com/mergeco/olijang/inquery/dto/InqCategoryDTO.java
- src/main/java/com/mergeco/olijang/inquery/dto/InqDTO.java
- src/main/java/com/mergeco/olijang/inquery/entity/InqCategory.java
- src/main/java/com/mergeco/olijang/inquery/entity/Inquiry.java
- src/main/java/com/mergeco/olijang/inquery/repository/InqCategoryRepository.java
- src/main/java/com/mergeco/olijang/inquery/repository/InqRepository.java
- src/main/java/com/mergeco/olijang/inquery/service/InqService.java
- src/main/java/com/mergeco/olijang/message/controller/MsgController.java
- src/main/java/com/mergeco/olijang/message/dto/MsgDTO.java
- src/main/java/com/mergeco/olijang/message/dto/MsgDeleteDTO.java
- src/main/java/com/mergeco/olijang/message/entity/Message.java
- src/main/java/com/mergeco/olijang/message/entity/MsgDelete.java
- src/main/java/com/mergeco/olijang/message/repository/MsgDeleteRepository.java
- src/main/java/com/mergeco/olijang/message/repository/MsgRepository.java
- src/main/java/com/mergeco/olijang/message/service/MsgService.java
- src/test/java/com/mergeco/olijang/inquery/InquiryTests.java
- src/test/java/com/mergeco/olijang/message/MessageTests.java
* * *
* * *
쪽지 및 1:1문의 구조 및 ENTITY작성
* * *
* * *
* * *
* * *
> [BE][FEATURE] 쪽지 및 1:1문의 구조 및 ENTITY작성

- build.gradle
- src/main/java/com/mergeco/olijang/user/entity/EnrollType.java
- src/main/java/com/mergeco/olijang/user/entity/User.java
- src/main/java/com/mergeco/olijang/user/model/dto/UserDTO.java
- src/main/java/com/mergeco/olijang/user/model/service/UserService.java
- src/main/java/com/mergeco/olijang/user/repository/UserRepository.java
- src/main/resources/application.yml
* * *
* * *
- 로그인 및 회원가입에 필요한 엔티티 작성
- 권한 설정에 필요한 build 및 yml 내용 추가
* * *
- build 내 하단의 내용 추가
```
implementation 'org.modelmapper:modelmapper:3.1.1'
implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
implementation 'com.googlecode.json-simple:json-simple:1.1.1'
implementation 'io.jsonwebtoken:jjwt:0.9.1'
```
- yml 내 하단 내용 추가
```
server:
port: 8000
spring:
jpa:
hibernate:
ddl-auto: none
properties:
hibernate:
format_sql: true
show_sql: true
datasource:
driver-class-name: com.mysql.cj.jdbc.Driver
url: jdbc:mysql://mysql.coffit.today:3306/oiljang
username: HIkdt6
password: HIkdt6
security:
oauth2:
client:
registration:
google:
client-id: 634314389152-hvham3k7rguk6i36b190d2adr0pi2ddb.apps.googleusercontent.com
client-secret: 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
scope: …
```
> 20231103 로그인 및 회원가입 Entity 추가

- src/main/java/com/mergeco/oiljang/report/controller/ReportController.java
- src/main/java/com/mergeco/oiljang/report/entity/Report.java
- src/main/java/com/mergeco/oiljang/report/entity/ReportCategory.java
- src/main/java/com/mergeco/oiljang/report/repository/ReportCategoryRepository.java
- src/main/java/com/mergeco/oiljang/report/repository/ReportRepository.java
- src/main/java/com/mergeco/oiljang/report/service/ReportService.java
- src/main/resources/application.yml
- src/test/java/com/mergeco/oiljang/product1/ProductControllerTests.java
- src/test/java/com/mergeco/oiljang/report/ReportTests.java
* * *
***
CRUD로 조회 테스트 코드 작성 하였습니다.
* * *
```
@DisplayName("TypedQuery를 이용한 단일 조회")
@DisplayName("Query를 이용한 단일 메뉴 조회 ")
@DisplayName("TypedQuery를 이용한 단일행 조회")
@DisplayName("TypedQuery를 이용한 다중행 조회")
@DisplayName("DISTINCT를 활용한 중복제거 조회")
@DisplayName("IN 연산자를 활용한 조회")
@DisplayName("LIKE 연산자를 활용한 조회")
```
등 조회 테스트 진행 하였습니다.
* * *
- 이름으로 조회하는 테스트 코드입니다. service 로직에서 작성하였습니다.
- LIKE 연산자도 활용이 좋지만 이름으로만 검색으로 유용할거 같아서 공유드립니다.
```
public List<Report> selectReportByBindingName(String nickName) {
String jpql = "SELECT m FROM tbl_report m WHERE m.reportUserNick = :reportUserNick";
List<Report> foundReportList = manager.createQuery(jpql, Report.class)
.setParameter("reportUserNick", nickName)
.getResultList();
return foundReportList;
} 
```
- 페이징 API 이용한 조회 테스트 코드 입니다.    
```
@DisplayName("페이징 API를 …
```
> [BE][FEATURE]신고기능 TDD

- src/main/java/com/mergeco/oiljang/inquery/dto/InqDTO.java
- src/main/java/com/mergeco/oiljang/inquery/dto/InqUserDTO.java
- src/main/java/com/mergeco/oiljang/inquery/entity/InqCategory.java
- src/main/java/com/mergeco/oiljang/inquery/entity/Inquiry.java
- src/main/java/com/mergeco/oiljang/inquery/repository/InqCategoryRepository.java
- src/main/java/com/mergeco/oiljang/inquery/repository/InqRepository.java
- src/main/java/com/mergeco/oiljang/message/controller/MsgController.java
- src/main/java/com/mergeco/oiljang/message/dto/MsgDTO.java
- src/main/java/com/mergeco/oiljang/message/dto/MsgDeleteDTO.java
- src/main/java/com/mergeco/oiljang/message/dto/MsgProInfoDTO.java
- src/main/java/com/mergeco/oiljang/message/dto/MsgUserDTO.java
- src/main/java/com/mergeco/oiljang/message/entity/Message.java
- src/main/java/com/mergeco/oiljang/message/entity/MsgDelete.java
- src/main/java/com/mergeco/oiljang/message/repository/MsgDeleteRepository.java
- src/main/java/com/mergeco/oiljang/message/repository/MsgRepository.java
- src/main/java/com/mergeco/oiljang/message/service/MsgService.java
- src/test/java/com/mergeco/oiljang/inquery/InquiryTests.java
- src/test/java/com/mergeco/oiljang/message/MessageTests.java
* * *
* * *
- message(쪽지)기능 테스트 개발 중, insert 진행중입니다.
* * *
- insert 관련 controller, service, test코드 추가했습니다
@SpringBootTest
public class MessageTests {
@Autowired
private MsgService msgService;
private static Stream<Arguments> getMsgInfos() {
LocalDate msgTime = LocalDate.parse("2023-11-06");
UUID sunsu = UUID.fromString("7b3ce47b-4080-49a5-b463-ecf3148117f4");
UUID bumbum = UUID.fromString("7b3ce47b-4080-49a5-b463-ecf3148117f4");
return Stream.of(
Arguments.of(1, "맥북 사고싶어요", "N", msgTime, 1,
"맥북팔아요", "새로 산 지 얼마 안돼서...", 1, sunsu, bumbum, 1, "N")
);
}
@DisplayName("쪽지 등록 테스트")
@ParameterizedTest
@MethodSource("getMsgInfos")
void msgInsertTest(int msgCode, String msgContent, String msgStatus,
LocalDate msgTime, int productCode, String productName,
String productDesc,int userCode, UUID …
> [BE][FEATURE]Message Insert TDD

- src/main/java/com/mergeco/oiljang/common/paging/Pagenation.java
- src/main/java/com/mergeco/oiljang/common/paging/PagingButton.java
- src/main/java/com/mergeco/oiljang/product/controller/ProductController.java
- src/main/java/com/mergeco/oiljang/product/dto/CategoryDTO.java
- src/main/java/com/mergeco/oiljang/product/dto/ProductDTO.java
- src/main/java/com/mergeco/oiljang/product/dto/ProductDetail.java
- src/main/java/com/mergeco/oiljang/product/dto/ProductList.java
- src/main/java/com/mergeco/oiljang/product/dto/SellStatusDTO.java
- src/main/java/com/mergeco/oiljang/product/entity/Category.java
- src/main/java/com/mergeco/oiljang/product/entity/ProImageInfo.java
- src/main/java/com/mergeco/oiljang/product/entity/Product.java
- src/main/java/com/mergeco/oiljang/product/entity/SellStatus.java
- src/main/java/com/mergeco/oiljang/product/repository/CategoryRepository.java
- src/main/java/com/mergeco/oiljang/product/repository/ProImageRepository.java
- src/main/java/com/mergeco/oiljang/product/service/CategoryService.java
- src/main/java/com/mergeco/oiljang/product/service/ProImageService.java
- src/main/java/com/mergeco/oiljang/product/service/ProductService.java
- src/main/java/com/mergeco/oiljang/wishlist/dto/WishListDTO.java
- src/main/java/com/mergeco/oiljang/wishlist/entity/WishList.java
- src/main/java/com/mergeco/oiljang/wishlist/repository/WishListRepository.java
- src/main/java/com/mergeco/oiljang/wishlist/service/WishListService.java
- src/test/java/com/mergeco/oiljang/product/ProductControllerTests.java
- src/test/java/com/mergeco/oiljang/wishlist/WishListControllerTests.java
* * *
Service 전반적인 부분을 구축했습니다. 다른 테이블에 있는 데이터는 예비로 만들었고, User, UserProfile도 만들어서 테스트 했습니다. 테스트 관련 코드도 작성했습니다.
Product, Category, WishList 등 기존 엔티티 변경과 ProductList, ProductDetail 등 조회한 결과를 담을 DTO를 만들었습니다. 
Pull 받을 시에 User, UserProfile관련 엔티티와, 레포지토리는 존재하지 않을 수 있습니다.
public Product category(int val) {
Category.categoryCode(val);
return this;
}
빌더 패턴에서 조인하는 엔티티 객체의 전체가 아니라 조인 컬럼의 값을 바꾸기 위한 메소드 입니다.
StringBuilder jpql = new StringBuilder("SELECT new com.mergeco.oiljang.product.dto.ProductList(m.productCode, (SELECT p.proImageThumbAddr FROM ProImageInfo p WHERE p.refProductCode = m.productCode), m.productName, m.productPrice, m.enrollDateTime, s.sellStatus)" +
" FROM Product m JOIN m.Category c JOIN m.SellStatus s WHERE m.Category.categoryCode = :categoryCode");
String jpql ="SELECT new …
> [BE][FEATURE]Product, WishList 관련 service 구현

- build.gradle
- src/main/java/com/mergeco/oiljang/auth/config/WebConfig.java
- src/main/java/com/mergeco/oiljang/auth/config/WebSecurityConfig.java
- src/main/java/com/mergeco/oiljang/auth/filter/CustomAuthenticationFilter.java
- src/main/java/com/mergeco/oiljang/auth/filter/HeaderFilter.java
- src/main/java/com/mergeco/oiljang/auth/filter/JwtAuthorizationFilter.java
- src/main/java/com/mergeco/oiljang/auth/handler/CustomAuthFailureHandler.java
- src/main/java/com/mergeco/oiljang/auth/handler/CustomAuthSuccessHandler.java
- src/main/java/com/mergeco/oiljang/auth/handler/CustomAuthenticationProvider.java
- src/main/java/com/mergeco/oiljang/auth/interceptor/JwtTokenInterceptor.java
- src/main/java/com/mergeco/oiljang/auth/model/DetailsUser.java
- src/main/java/com/mergeco/oiljang/auth/model/dto/JoinDTO.java
- src/main/java/com/mergeco/oiljang/auth/model/dto/LoginDTO.java
- src/main/java/com/mergeco/oiljang/auth/model/service/DetailsService.java
- src/main/java/com/mergeco/oiljang/common/AuthConstants.java
- src/main/java/com/mergeco/oiljang/common/UserRole.java
- src/main/java/com/mergeco/oiljang/common/utils/ConvertUtil.java
- src/main/java/com/mergeco/oiljang/common/utils/TokenUtils.java
- src/main/java/com/mergeco/oiljang/user/controller/UserController.java
- src/main/java/com/mergeco/oiljang/user/entity/EnrollType.java
- src/main/java/com/mergeco/oiljang/user/entity/User.java
- src/main/java/com/mergeco/oiljang/user/model/service/UserService.java
- src/main/java/com/mergeco/oiljang/user/repository/UserRepository.java
- src/main/resources/application.yml
* * *
* * *
- 로그인 및 회원가입에 필요한 DTO 추가
- JWT 설정에 필요한 파일 추가 및 수정
* * *
- 필터, 핸들러 파일 추가
- 소셜 로그인 및 회원 가입 구현을 위한 build 내 하단의 내용 추가
```
implementation 'com.auth0:java-jwt:4.4.0'
```
- 소셜 로그인 및 회원 가입에 필요한 파일 추가
* * *
- OAuth2 관련 내용 주석 처리
- 소셜 로그인 이외의 기능 구현 jwt 설정 완료
- enrolltype 관련 오류로 인한 임의로 normal 설정
* * *
- 일반 회원가입(insert) 테스트 완료 
- 일반 로그인(select) 테스트 완료
* * *
- User 관련한 dto 및 엔티티 사용 시 코멘트 부탁드립니다.
> [BE][FEATURE] JWT 설정 추가

- build.gradle
- src/main/java/com/mergeco/oiljang/auth/config/WebSecurityConfig.java
- src/main/java/com/mergeco/oiljang/auth/filter/HeaderFilter.java
- src/main/java/com/mergeco/oiljang/auth/filter/JwtAuthorizationFilter.java
- src/main/java/com/mergeco/oiljang/auth/model/dto/JoinDTO.java
- src/main/java/com/mergeco/oiljang/auth/model/dto/LoginDTO.java
- src/main/java/com/mergeco/oiljang/common/exception/UserErrorResult.java
- src/main/java/com/mergeco/oiljang/common/exception/UserException.java
- src/main/java/com/mergeco/oiljang/common/utils/ConvertUtil.java
- src/main/java/com/mergeco/oiljang/common/utils/TokenUtils.java
- src/main/java/com/mergeco/oiljang/user/controller/UserController.java
- src/main/java/com/mergeco/oiljang/user/entity/User.java
- src/main/java/com/mergeco/oiljang/user/entity/UserProfile.java
- src/main/java/com/mergeco/oiljang/user/model/dto/UserDTO.java
- src/main/java/com/mergeco/oiljang/user/model/dto/UserProfileDTO.java
- src/main/java/com/mergeco/oiljang/user/model/service/UserService.java
- src/main/java/com/mergeco/oiljang/user/repository/UserRepository.java
- src/test/java/com/mergeco/oiljang/user/UserTests.java
* * *
* * *
- 회원가입 시 프로필 등록 기능
- 회원가입에 대한 테스트 
* * *
- 프로필 등록에 필요한 엔티티 추가
- 프로필 등록으로 인한 USER 엔티티 내용 수정
- 회원가입 시 프로필와 함께 등록하기 위한 TEST 파일 추가
- 필요없는 test 기반 폴더 및 파일 삭제
* * *
- 프로필 등록에 따른 회원가입 테스트 진행 중 
- 구동 시 문제되는 부분 주석처리
* * *
- ref_user_code로 인한 오류 발생
* * *
- USER 엔티티 또는 DTO 사용 시 말씀해주세요.
> [BE][FEATURE] 회원가입 프로필 등록 추가

- build.gradle
- src/main/java/com/mergeco/oiljang/auth/config/WebConfig.java
- src/main/java/com/mergeco/oiljang/auth/model/DetailsUser.java
- src/main/java/com/mergeco/oiljang/common/utils/TokenUtils.java
- src/main/java/com/mergeco/oiljang/config/FileUploadConfig.java
- src/main/java/com/mergeco/oiljang/user/controller/UserController.java
- src/main/java/com/mergeco/oiljang/user/entity/User.java
- src/main/java/com/mergeco/oiljang/user/entity/UserProfile.java
- src/main/java/com/mergeco/oiljang/user/model/service/UserService.java
- src/main/java/com/mergeco/oiljang/user/repository/UserProfileRepository.java
- src/main/resources/application.yml
- src/test/java/com/mergeco/oiljang/user/UserTests.java
* * *
* * *
- 회원가입 시 프로필 등록 기능
- 회원가입에 대한 테스트
* * *
- 프로필 파일 등록을 위한 엔티티 수정
- 프로필 등록으로 인한 service 및 controller 수정
- 테스트를 위한 회원가입 test 파일 수정
- file 업로드 관련 build 및 yml 내용 추가
[yml파일]
```
servlet:
multipart:
max-file-size: 100MB
max-request-size: 100MB
file:
upload-dir: C:\Users\User\Desktop\dir\upload
```
[gradle파일]
```
implementation 'net.coobird:thumbnailator:0.4.14'
implementation 'commons-fileupload:commons-fileupload:1.5'
```
- USER 엔티티 필드명 변경(userId->userCode)
* * *
- file upload 관련 수정 진행 중
- 구동 시 문제되는 부분 주석처리
- 파일 업로드에 필요한 설정 내용 추가
* * *
- 회원가입 TDD 진행 및 성공
- API 테스트 진행 및 실패
- POSTMAN 테스트 문서
https://web.postman.co/workspace/My-Workspace~7cf9a488-5531-420d-8524-46fd2b7a3ccf/documentation/30517729-db3fbdb4-c43e-430d-a3d5-a26efea0f534
* * *
- user 엔티티 사용 시 말씀해주세요.
> [BE][FEATURE] 회원가입 프로필 등록 수정

- src/main/java/com/mergeco/oiljang/report/entity/Report.java
- src/main/java/com/mergeco/oiljang/report/model/dto/ReportCategoryDTO.java
- src/main/java/com/mergeco/oiljang/report/model/dto/ReportDTO.java
- src/main/java/com/mergeco/oiljang/report/repository/ReportRepository.java
- src/main/java/com/mergeco/oiljang/report/service/ReportService.java
- src/test/java/com/mergeco/oiljang/report/ReportTests.java
* * *
* * *
- TDD insert 테스트 진행중입니다.
* * *
```
package com.mergeco.oiljang.report.model.dto;
import com.mergeco.oiljang.product.dto.ProductDTO;
import com.mergeco.oiljang.product.dto.SellStatusDTO;
import lombok.*;
import java.time.LocalDateTime;
@ToString
@Setter
@Getter
@AllArgsConstructor
@NoArgsConstructor
public class ReportDTO {
private int reportNo; // 신고 번호
private String reportUserNick; // 신고자
private String reportComment; // 신고 내용
private LocalDateTime reportDate; //신고일시
private String productName; // 상품 코드 -> 판매글
private String sellStateus; // 판매상태코드 -> 판매중인지 예약중인지.
private int reportCategoryNo; // 신고분류 코드 FK -> 광고성 , 사기의심
private String processDistincation; // 처리분류 => null
private String processComment; // 처리 내용  null
private LocalDateTime processDate; // 처리 일시 null
public …
```
> :bug:[BE][FEATURE] 신고기능 TDD (Insert)

- src/main/java/com/mergeco/oiljang/inquery/entity/Inquiry.java
- src/main/java/com/mergeco/oiljang/message/controller/MsgController.java
- src/main/java/com/mergeco/oiljang/message/dto/MsgInsertDTO.java
- src/main/java/com/mergeco/oiljang/message/dto/MsgListDTO.java
- src/main/java/com/mergeco/oiljang/message/dto/MsgProUserInfoDTO.java
- src/main/java/com/mergeco/oiljang/message/dto/MsgReceiverDTO.java
- src/main/java/com/mergeco/oiljang/message/dto/MsgUserDTO.java
- src/main/java/com/mergeco/oiljang/message/entity/Message.java
- src/main/java/com/mergeco/oiljang/message/repository/MsgRepository.java
- src/main/java/com/mergeco/oiljang/message/service/MsgService.java
- src/test/java/com/mergeco/oiljang/message/MessageTests.java
* * *
* * *
- 쪽지 상세 조회까지 성공
- sender receiver 조건 조회 구현중
- isReceived 조건 서비스에서 구현하는데 조금 어렵습니다 하하..
* * *
- 쪽지 상세조회
public List<MsgProUserInfoDTO> selectMsgDetail(int msgCode) {
String jpql = "SELECT new com.mergeco.oiljang.message.dto.MsgProUserInfoDTO(m.msgCode, m.msgContent, m.msgStatus, m.msgTime, m.senderCode, m.receiverCode, u.userCode, u.id, u.name, p.productCode, p.productName, p.productDesc, md.msgDeleteCode, md.msgDeleteStatus) "
+ "FROM message_and_delete m "
+ "LEFT JOIN User u ON m.senderCode = u.userCode OR m.receiverCode = u.userCode "
+ "LEFT JOIN Product p ON m.refProductCode = p.productCode "
+ "LEFT JOIN m.msgDeleteInfo md "
+ "WHERE m.msgCode = :msgCode";
List<MsgProUserInfoDTO> msgProUserList = entityManager.createQuery(jpql, MsgProUserInfoDTO.class) …
> [BE][FEATURE]쪽지 상세 조회까지 성공, sender receiver 조건 조회 구현중

- src/main/java/com/mergeco/oiljang/report/controller/ReportController.java
- src/main/java/com/mergeco/oiljang/report/dto/ReportCategoryDTO.java
- src/main/java/com/mergeco/oiljang/report/dto/ReportDTO.java
- src/main/java/com/mergeco/oiljang/report/entity/ReportCategory.java
- src/main/java/com/mergeco/oiljang/report/service/ReportService.java
- src/test/java/com/mergeco/oiljang/report/ReportTests.java
* * *
* * *
- Swagger를 이용한 신고 CRUD 진행중입니다.
* * *
-     
```
@ApiOperation(value = "신고관리")
@GetMapping("/reportManagerment")
public ResponseEntity<ResponseMessage> findReportManagement() {
List<Object[]> management = reportService.selectByReportManagement();
Map<String, Object> responseMap = new HashMap<>();
responseMap.put("management", management);
ResponseMessage responseMessage = new ResponseMessage(200, "신고관리", responseMap);
return new ResponseEntity<>(responseMessage, getHeaders(), HttpStatus.OK);
}
```
- 신고관리 또는 신고처리 swagger 작성하였습니다.
* * *
```
/*    @ApiOperation(value = "신고하기")
@GetMapping("/report")
public ResponseEntity<?> registReport(@RequestBody ReportDTO report) {
System.out.println("insertReport : " + report);
Report report = reportService.insertReport();
}*/
```
현재 …
> :bug: [BE][FEATURE] 신고 CRUD Swagger

- src/main/java/com/mergeco/oiljang/product/controller/ProductController.java
- src/main/java/com/mergeco/oiljang/product/dto/SellingListDTO.java
- src/main/java/com/mergeco/oiljang/product/service/ProductService.java
* * *
* * *
- 판매목록 조회를 위헤 SellStatusDTO를 하나 만들었습니다
* * *
> [BE][FEATURE]상품 이미지 업로드 DB 접속 완료 & 판매목록 조회

- sql/oilJangSql.sql
- src/main/java/com/mergeco/oiljang/product/controller/ProductController.java
- src/main/java/com/mergeco/oiljang/product/dto/ProductDTO.java
- src/main/java/com/mergeco/oiljang/product/dto/ProductDetailDTO.java
- src/main/java/com/mergeco/oiljang/product/entity/Product.java
- src/main/java/com/mergeco/oiljang/product/service/ProductService.java
- src/main/java/com/mergeco/oiljang/wishlist/controller/WishListController.java
- src/main/java/com/mergeco/oiljang/wishlist/dto/WishListDTO.java
- src/main/java/com/mergeco/oiljang/wishlist/entity/WishList.java
- src/main/java/com/mergeco/oiljang/wishlist/service/WishListService.java
- src/test/java/com/mergeco/oiljang/product/ProductTests.java
- src/test/java/com/mergeco/oiljang/wishlist/WishListTests.java
* * *
user_code 데이터 타입을 UUID에서 int로 수정함에 따라 엔티티, DTO, 로직을 수정했습니다.
ref_user_code 엔티티 필드, DTO 필드 데이터 타입을 int로 변경했습니다.
로직도 UUID에서 int 데이터 타입으로 변경했습니다.
로컬 DB에서 product_info 테이블의  칼럼 중에 UUID가 있는 경우 제대로 작동을 안 할 수도 있습니다.
추가가 product/wishlist controller 관련 테스트도 성공했습니다. 
로컬 DB는 6차 스크립트를 적용해주세요. UUID를 int로 바꾼 버전입니다.
> [BE][FEATURE] user_code 관련된 부분 int로 수정하기

- src/main/java/com/mergeco/oiljang/auth/config/WebSecurityConfig.java
- src/main/java/com/mergeco/oiljang/auth/filter/HeaderFilter.java
- src/main/java/com/mergeco/oiljang/auth/handler/JwtAccessDeniedHandler.java
- src/main/java/com/mergeco/oiljang/auth/handler/JwtAuthenticationEntryPoint.java
- src/main/java/com/mergeco/oiljang/user/controller/UserController.java
- src/main/java/com/mergeco/oiljang/user/entity/User.java
- src/main/java/com/mergeco/oiljang/user/entity/UserProfile.java
- src/main/java/com/mergeco/oiljang/user/model/service/UserService.java
- src/main/java/com/mergeco/oiljang/user/repository/UserRepository.java
- src/main/resources/application.yml
- src/test/java/com/mergeco/oiljang/user/UserTests.java
* * *
* * *
- jwt 설정 수정
- 아이디 중복 추가
- yml db접속 내용 변경
* * *
- 접근 불가로 인한 jwt 설정 수정
- 순환 참조로 인한 문제로 handler 및 엔티티 수정
- 공유하고 있는 DB로 변경
* * *
- 로그인 중복 검사 TEST 진행 중
- 로그인 중복 검사 Swagger-ui 작업 중
* * *
- 회원 정보 insert는 성공
- 로그인 중복 체크 로직 test 진행 중
* * *
- jwt 설정으로 인한 문제가 있는지 확인부탁드립니다.
> [BE][FEATURE] JWT 수정 및 아이디 중복 추가

- src/main/java/com/mergeco/oiljang/message/controller/MsgController.java
- src/main/java/com/mergeco/oiljang/message/dto/MsgListDTO.java
- src/main/java/com/mergeco/oiljang/message/repository/MsgRepository.java
- src/main/java/com/mergeco/oiljang/message/service/MsgService.java
- src/test/java/com/mergeco/oiljang/message/MessageTests.java
* * *
* * *
- 받은 쪽지함, 보낸 쪽지함 조회 구현
```  
public List<MsgListDTO> getMessages(int userCode, int offset, int limit, Boolean isReceived) {
String jpql;
if (isReceived != null && isReceived) {
jpql = "SELECT new com.mergeco.oiljang.message.dto.MsgListDTO(u.userCode, m.senderCode, m.receiverCode, m.msgContent, m.msgStatus, m.msgTime, md.msgDeleteCode) "
+ "FROM message_and_delete m "
+ "LEFT JOIN User u ON m.receiverCode = :userCode "
+ "LEFT JOIN m.msgDeleteInfo md "
+ "WHERE m.receiverCode = :userCode AND md.msgDeleteCode IN (1, 2)";
} else {
jpql = "SELECT new com.mergeco.oiljang.message.dto.MsgListDTO(u.userCode, m.senderCode, m.receiverCode, m.msgContent, m.msgStatus, m.msgTime, md.msgDeleteCode) "
+ "FROM message_and_delete m "
+ "LEFT JOIN User u ON m.senderCode = :userCode "
+ "LEFT …
```
> [BE][FEATURE]쪽지리스트 조회 SENDER/RECEIVER 조건 구현(좀 더 손봐야함)

- src/main/java/com/mergeco/oiljang/auth/config/WebSecurityConfig.java
- src/main/java/com/mergeco/oiljang/auth/filter/CustomAuthenticationFilter.java
- src/main/java/com/mergeco/oiljang/auth/filter/HeaderFilter.java
- src/main/java/com/mergeco/oiljang/auth/handler/CustomAuthSuccessHandler.java
- src/main/java/com/mergeco/oiljang/auth/handler/TokenProvider.java
- src/main/java/com/mergeco/oiljang/auth/model/DetailsUser.java
- src/main/java/com/mergeco/oiljang/auth/model/dto/TokenDTO.java
- src/main/java/com/mergeco/oiljang/auth/model/service/DetailsService.java
- src/main/java/com/mergeco/oiljang/common/restApi/LoginMessage.java
- src/main/java/com/mergeco/oiljang/common/restApi/ResponseMessage.java
- src/main/java/com/mergeco/oiljang/common/utils/TokenUtils.java
- src/main/java/com/mergeco/oiljang/user/controller/UserController.java
- src/main/java/com/mergeco/oiljang/user/model/service/UserService.java
- src/main/java/com/mergeco/oiljang/user/repository/UserRepository.java
- src/test/java/com/mergeco/oiljang/user/UserTests.java
* * *
- #5 
* * *
* * *
- 로그인 기능 수정
- 아이디 및 닉네임 중복확인 추가
* * *
- 로그인 기능 수정
- 아이디 및 닉네임 중복확인 추가
* * *
- 현재 로그인 기능 테스트 중
- UserRole 부분 수정 필요
* * *
- 아이디 및 닉네임 중복 테스트 완료
- 로그인 테스트 실패
```
1) Failed to instantiate instance of destination com.mergeco.oiljang.common.UserRole. Ensure that com.mergeco.oiljang.common.UserRole has a non-private no-argument constructor.
1 error
at org.modelmapper.internal.Errors.throwMappingExceptionIfErrorsExist(Errors.java:386) ~[modelmapper-3.1.1.jar:na]
at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:80) ~[modelmapper-3.1.1.jar:na]
at org.modelmapper.ModelMapper.mapInternal(ModelMapper.java:589) ~[modelmapper-3.1.1.jar:na]
at org.modelmapper.ModelMapper.map(ModelMapper.java:422) ~[modelmapper-3.1.1.jar:na]
at …
```
> [BE][Feature] 로그인 기능 수정

- src/main/java/com/mergeco/oiljang/product/controller/ProductController.java
- src/main/java/com/mergeco/oiljang/product/service/ProductService.java
- src/test/java/com/mergeco/oiljang/product/ProductTests.java
* * *
- [BE][FEATURE]상품 삭제 #60 
* * *
* * *
``
@ApiOperation(value = "중고 상품 삭제")
@DeleteMapping(value = "/products/{productCode}")
public ResponseEntity<ResponseMessage> deleteProduct(@PathVariable int productCode) {
HttpHeaders headers = new HttpHeaders();
headers.setContentType(new MediaType("application", "json", Charset.forName("UTF-8")));
productService.updateSellStatusToDeleted(productCode);
ResponseMessage responseMessage = new ResponseMessage(200, "상품 삭제 성공", null);
return new ResponseEntity<>(responseMessage, headers, HttpStatus.OK);
}
``
* * *
- 데이터가 없어서 결과는 아직 안 나왔습니다.
* * *
- 데이터가 없어서 결과는 아직 안 나왔습니다.
> [BE][FEATURE]상품 삭제 진행중

- src/main/java/com/mergeco/oiljang/report/controller/ReportController.java
- src/main/java/com/mergeco/oiljang/report/dto/ReportDTO.java
- src/main/java/com/mergeco/oiljang/report/entity/Report.java
- src/main/java/com/mergeco/oiljang/report/entity/ReportCategory.java
- src/main/java/com/mergeco/oiljang/report/service/ReportService.java
* * *
- #65 
* * *
* * *
- 신고 기능 업데이트 수정 완료하였습니다.
* * *
```
@Transactional
public Object modifyReport(@RequestBody ReportDTO reportDTO) {
log.info("[reportService] updateReport Start ================================================");
int result = 0;
try {
Report report = reportRepository.findById(reportDTO.getReportNo()).get();
log.info("Repository Check : " + report);
report = report
.processDistinction(reportDTO.getProcessDistinction())
.processComment(reportDTO.getProcessComment())
.processDate(reportDTO.getProcessDate())
.sellStatus(reportDTO.getSellStatus())
.build();
result = 1;
} catch (Exception e) {
log.info("[Report update] Exception !!" + e);
}
log.info("[reportService] updateReport END ===============================================");
return (result > 0) ? "처리 완료" : "처리 실패"; …
```
> :technologist: [BE][FEATURE] 신고기능 CRUD 완료

- src/main/java/com/mergeco/oiljang/message/controller/MsgController.java
- src/main/java/com/mergeco/oiljang/message/dto/MsgDTO.java
- src/main/java/com/mergeco/oiljang/message/entity/Message.java
- src/main/java/com/mergeco/oiljang/message/repository/MsgRepository.java
- src/main/java/com/mergeco/oiljang/message/service/MsgService.java
- src/test/java/com/mergeco/oiljang/message/MessageTests.java
* * *
- #51 
* * *
* * *
- 쪽지 상세 조회 시 쪽지 읽음 여부 상태값 변경(데이터가 없어서 결과 확인은 아직)
```
@Transactional
public void updateMsgStatus(int msgCode) {
Message message = msgRepository.findById(msgCode).orElseThrow(IllegalArgumentException::new);
message = message.msgStatus("Y").builder();
msgRepository.save(message);
System.out.println(message);
}
```
- 쪽지 삭제 시 상태값 변경 로직 구현 중
* * *
- 쪽지 상세 조회 시 쪽지 읽음 여부 상태값 변경(데이터가 없어서 결과 확인은 아직)
- 쪽지 삭제 시 상태값 변경 로직 구현 중
* * *
- 데이터가 없어서 결과 확인은 아직
* * *
- 데이터가 없어서 결과 확인은 아직
* * *
> [BE][FEATURE] 쪽지 수정 기능 구현중

- src/main/java/com/mergeco/oiljang/product/controller/ProductController.java
- src/main/java/com/mergeco/oiljang/product/dto/ProductDTO.java
- src/main/java/com/mergeco/oiljang/product/entity/Product.java
- src/main/java/com/mergeco/oiljang/product/repository/ProductRepository.java
- src/main/java/com/mergeco/oiljang/product/service/ProductService.java
* * *
-  #59 
* * *
* * *
- existingProduct.productName(updatedProductDTO.getProductName()): updatedProductDTO에서 새 제품 이름을 가져와서 해당 제품의 이름을 업데이트를 하게 했습니다.
- existingProduct.productPrice(updatedProductDTO.getProductPrice()): 새 제품 가격을 가져와서 해당 제품의 가격을 업데이트하게 했습니다
* * *
``
@Transactional
public void updateProductInfo(int productCode, ProductDTO updatedProductDTO) {
// 업데이트할 상품을 조회
Product existingProduct = productRepository.findById(productCode)
.orElseThrow(IllegalArgumentException::new);
System.out.println(existingProduct);
System.out.println(updatedProductDTO);
// 새로운 정보로 업데이트
existingProduct.productName(updatedProductDTO.getProductName());
existingProduct.productPrice(updatedProductDTO.getProductPrice());
String productDesc = updatedProductDTO.getProductDesc();
if (productDesc != null) { …
> [BE][Feature] 상품 수정 완료

- src/main/java/com/mergeco/oiljang/report/controller/ReportController.java
- src/main/java/com/mergeco/oiljang/report/service/ReportService.java
- src/test/java/com/mergeco/oiljang/report/ReportTests.java
* * *
- #63 
* * *
* * *
- 리액트에서 API요청시 인덱스로 값을 받아 와서 전체 조회로 변경하였습니다.
* * *
- 기존에는 jpql로직을 이용하여 컬럼별로 조회 하였습니다.
- 
```
public List<Report> findReports() {
log.info("[reportService] selectReport  ================================================");
return reportRepository.findAll();
} 
```
- 변경된 서비스 로직입니다.
* * *
- 인덱스로 값을 받아 와서 배열이 아닌상태여서 
- 값을 리액트에서 변경하여 사용에 어려움이 있어 변경하였습니다.
* * *
* * *
> :bug: [BE][FEATURE] 신고기능 전체조회 변경

- src/main/java/com/mergeco/oiljang/inquery/controller/InqController.java
- src/main/java/com/mergeco/oiljang/inquery/dto/InqCategoryDTO.java
- src/main/java/com/mergeco/oiljang/inquery/dto/InqDTO.java
- src/main/java/com/mergeco/oiljang/inquery/dto/InqInsertDTO.java
- src/main/java/com/mergeco/oiljang/inquery/dto/InqUserDTO.java
- src/main/java/com/mergeco/oiljang/inquery/entity/Inquiry.java
- src/main/java/com/mergeco/oiljang/inquery/service/InqService.java
- src/main/java/com/mergeco/oiljang/message/controller/MsgController.java
- src/main/java/com/mergeco/oiljang/message/dto/MsgListDTO.java
- src/main/java/com/mergeco/oiljang/message/entity/Message.java
- src/main/java/com/mergeco/oiljang/message/service/MsgService.java
- src/test/java/com/mergeco/oiljang/inquery/InquiryTests.java
- src/test/java/com/mergeco/oiljang/message/MessageTests.java
* * *
- #51 
* * *
* * *
- 쪽지 수정기능 수정중입니다.
```
private boolean isDeletedBySender(int sender, MsgDeleteInfo msgDeleteInfo){
if(msgDeleteInfo.getMsgDeleteCode() == 1){
return true;
}
return false;
}
private boolean isDeletedByReceiver(int receiver, MsgDeleteInfo msgDeleteInfo){
if(msgDeleteInfo.getMsgDeleteCode() == 2){
return true;
}
return false;
}
@Transactional
public int updateDeleteCode(int msgCode) {
int result = 0;
try {
Message message = msgRepository.findById(msgCode).orElseThrow(IllegalArgumentException::new);
System.out.println("service : " + msgCode);
int sender = message.getSenderCode();
int receiver = message.getReceiverCode();
//builder를 쓰면 새로 받아줘야하고, 현재 영속화 된 엔티티는 Message이기 때문에 , MsgDeleteInfo를 새로 객체생성해서 값을 받아줬으면
//해당 값들을 다시 Message엔티티에 세팅해줘야한다.
System.out.println("sender : …
```
> [BE][FEATURE] 쪽지 수정기능 수정중

- src/main/java/com/mergeco/oiljang/common/paging/JpqlPagingButton.java
- src/main/java/com/mergeco/oiljang/product/controller/ProductController.java
- src/main/java/com/mergeco/oiljang/product/dto/ProductListDTO.java
- src/main/java/com/mergeco/oiljang/product/entity/Product.java
- src/main/java/com/mergeco/oiljang/product/service/ProductService.java
- src/test/java/com/mergeco/oiljang/product/service/ProductServiceTests.java
#9 
* * *
* * *
프론트 작업 중 상품 조회 관련 백엔드 수정이 필요하여 작업을 진행했습니다.
* * *
메인 페이지 상품 목록 출력 관련 로직을 만들었습니다.
BE/assets/136870051/d57613c9-60b3-4702-aac7-d469b7b3c2b0)
상품 목록 관련 JSON에서 판매상태를 빼고 카테고리 이름을 넣었습니다. 이에 따라 ProductController, ProductService와 ProductListDTO를 변경했습니다.
* * *
* * *
* * *
> [BE][FEATURE] 상품 조회 관련 매개변수와 보내주는 결과 수정

- src/main/java/com/mergeco/oiljang/auth/config/JwtSecurityConfig.java
- src/main/java/com/mergeco/oiljang/auth/config/WebSecurityConfig.java
- src/main/java/com/mergeco/oiljang/auth/filter/CustomAuthenticationFilter.java
- src/main/java/com/mergeco/oiljang/auth/filter/JwtFilter.java
- src/main/java/com/mergeco/oiljang/auth/handler/CustomAuthSuccessHandler.java
- src/main/java/com/mergeco/oiljang/auth/handler/CustomAuthenticationProvider.java
- src/main/java/com/mergeco/oiljang/auth/handler/JwtAccessDeniedHandler.java
- src/main/java/com/mergeco/oiljang/auth/handler/JwtAuthenticationEntryPoint.java
- src/main/java/com/mergeco/oiljang/auth/handler/TokenProvider.java
- src/main/java/com/mergeco/oiljang/auth/model/DetailsUser.java
- src/main/java/com/mergeco/oiljang/auth/model/service/DetailsService.java
- src/main/java/com/mergeco/oiljang/common/AuthConstants.java
- src/main/java/com/mergeco/oiljang/common/UserRole.java
- src/main/java/com/mergeco/oiljang/common/utils/TokenUtils.java
- src/main/java/com/mergeco/oiljang/user/controller/UserController.java
- src/main/java/com/mergeco/oiljang/user/entity/User.java
- src/main/java/com/mergeco/oiljang/user/entity/UserProfile.java
- src/main/java/com/mergeco/oiljang/user/model/dto/UserDTO.java
- src/main/java/com/mergeco/oiljang/user/model/service/UserService.java
- src/test/java/com/mergeco/oiljang/auth/AuthTests.java
- src/test/java/com/mergeco/oiljang/user/UserTests.java
* * *
- #8 
- #66 
- #68 
- #67 
* * *
* * *
- 토큰 발급이 안되는 버그 수정
- 토큰 발급 검증 버그 수정
- 토큰 발급 수정으로 인한 join 버그 수정
- 회원 탈퇴 기능 추가
* * *
- jwt 토큰 인증 설정 변경
- 회원 탈퇴 기능 추가로 인한 dto 수정 및 서비스 로직 추가
- 토큰 발급 로직 수정
- 토큰 검증 안되는 버그로 인한 authentication 관련 로직 수정
* * *
- 아이디 및 비밀번호 모두 틀릴 경우 서버 오류가 발생하는 부분 수정 중 입니다.
* * *
- 로그인 기능 테스트(성공)
- 회원 가입 기능 테스트(성공)
- 회원 정보 조회 테스트(성공)
- 회원 정보 수정 테스트(성공)
- 회원 탈퇴 테스트(성공)
* * *
- 토큰 검증 버그 수정으로 인한 기능 테스트 시 토큰을 발급받고 토큰값을 넣은 다음에 테스트 진행하셔야합니다.
> [BE][Feature] 회원가입 기능 수정

- src/main/java/com/mergeco/oiljang/inquiry/controller/InqController.java
- src/main/java/com/mergeco/oiljang/inquiry/service/InqService.java
- src/test/java/com/mergeco/oiljang/inquiry/InquiryTests.java
* * *
- #55 
* * *
* * *
- 1:1문의 삭제 기능 구현
* * *
- 1:1문의에 삭제 기능 추가했습니다
```
@Test
@DisplayName("문의 삭제")
public void deleteInq(){
int inqCode = 1;
int result = inqService.deleteInq(inqCode);
Assertions.assertEquals(1, result);
}
```
```
@Transactional
public int deleteInq(int inqCode) {
int result = 0;
try{
inqRepository.deleteById(inqCode);
result = 1;
}catch (Exception e){
System.out.println("실패~");
}
return (result > 0) ? 1 : -1;
}
```
```
@ApiOperation(value = "문의 삭제")
@DeleteMapping("/inquiries/{inqCode}")
public ResponseEntity<ResponseMessage> deleteInq(@PathVariable int inqCode){
HttpHeaders headers = new HttpHeaders();
headers.setContentType(new MediaType("application", "json", Charset.forName("UTF-8")));
int result = inqService.deleteInq(inqCode);
System.out.println("result : " + …
```
> [BE][FEATURE]1:1문의 삭제 기능 완료

- src/main/java/com/mergeco/oiljang/message/service/MsgService.java
* * *
- #48 
* * *
* * *
- 쪽지 키워드로 조회하는 로직 수정했습니다.
* * *
- like 연산자 로직 수정했습니다
- 빈 값일 경우에 검증하는 로직 추가했습니다.
```
public List<MsgListDTO> selectMsgLike(int userCode, int offset, int limit, Boolean isReceived, String keyword) {
String jpql;
if(keyword == null || keyword.equals("")) {
keyword = "";
if ((isReceived != null && isReceived)) {
jpql = "SELECT new com.mergeco.oiljang.message.dto.MsgListDTO(u.userCode, u.name, u.id, m.senderCode, m.receiverCode, m.msgContent, m.msgStatus, m.msgTime, md.msgDeleteCode) "
+ "FROM message_and_delete m "
+ "LEFT JOIN User u ON m.receiverCode = u.userCode "
+ "JOIN m.msgDeleteInfo md "
+ "WHERE m.receiverCode = :userCode AND md.msgDeleteCode IN (1, 2) AND m.senderCode <> u.userCode";
} else {
jpql = "SELECT new …
```
> [BE][BUG]쪽지 키워드 조회 수정

- src/main/java/com/mergeco/oiljang/auth/config/OAuth2Config.java
- src/main/java/com/mergeco/oiljang/auth/config/WebSecurityConfig.java
- src/main/java/com/mergeco/oiljang/auth/filter/CustomAuthenticationFilter.java
- src/main/java/com/mergeco/oiljang/auth/filter/JwtFilter.java
- src/main/java/com/mergeco/oiljang/auth/handler/CustomAuthenticationProvider.java
- src/main/java/com/mergeco/oiljang/auth/handler/OAuth2LoginHandler.java
- src/main/java/com/mergeco/oiljang/auth/handler/OAuth2SuccessHandler.java
- src/main/java/com/mergeco/oiljang/auth/model/DetailsUser.java
- src/main/java/com/mergeco/oiljang/auth/model/dto/OAuth2LoginDTO.java
- src/main/java/com/mergeco/oiljang/auth/model/dto/OAuth2LoginResponseDTO.java
- src/main/java/com/mergeco/oiljang/auth/model/service/DetailsService.java
- src/main/java/com/mergeco/oiljang/auth/model/service/OAuth2DetailsService.java
- src/main/java/com/mergeco/oiljang/common/utils/TokenUtils.java
- src/main/java/com/mergeco/oiljang/user/controller/OAuth2Controller.java
- src/main/java/com/mergeco/oiljang/user/model/service/OAuth2Service.java
- src/main/java/com/mergeco/oiljang/user/repository/CustomOAuth2AuthorizationRequestRepository.java
- src/main/java/com/mergeco/oiljang/user/repository/UserRepository.java
- src/main/resources/application.yml
* * *
- #5 
* * *
* * *
- 소셜 로그인 관련 기능 추가
* * *
- 소셜 로그인으로 인한 시큐리티, yml 내용 수정
* * *
- 아직 프론트엔드에서 테스트를 하지 못했습니다.
- 프론트엔드 구현 중입니다. 
* * *
- 진행 중
* * *
- 시큐리티 설정 변경으로 인한 로그인 및 토큰을 못 가져오는 문제가 발생할 경우 말씀해주세요.
> [BE][Feature] 로그인  기능

- src/main/java/com/mergeco/oiljang/product/controller/ProductController.java
- src/main/java/com/mergeco/oiljang/product/dto/ProductListDTO.java
- src/main/java/com/mergeco/oiljang/product/service/ProductService.java
- src/main/java/com/mergeco/oiljang/wishlist/dto/WishListInfoDTO.java
- src/main/java/com/mergeco/oiljang/wishlist/service/WishListService.java
- src/test/java/com/mergeco/oiljang/product/controller/ProductControllerTests.java
* * *
- #9 
* * *
* * *
- 프론트 엔트 상황에 따라 백엔드를 변경했습니다. 조회수, 페이징, 판매자정보, 유저 정보 등등
* * *
- productController, productService, productListDTO 등에서 보내주는 정보와 순서를 변경했습니다.
* * *
* * *
* * *
변경으로 인해 문제가 생긴다면 말씀해주세요.
> [BE][Feature] 상품 조회시 백엔드에서 보내주는 데이터 변경

- src/main/java/com/mergeco/oiljang/config/BeanConfiguration.java
- src/main/java/com/mergeco/oiljang/report/controller/ReportController.java
- src/main/java/com/mergeco/oiljang/report/dto/ReportDTO.java
- src/main/java/com/mergeco/oiljang/report/entity/Report.java
- src/main/java/com/mergeco/oiljang/report/repository/ReportRepository.java
- src/main/java/com/mergeco/oiljang/report/service/ReportService.java
- src/test/java/com/mergeco/oiljang/product/service/ProductServiceTests.java
- src/test/java/com/mergeco/oiljang/report/ReportTests.java
* * *
- #90
* * *
* * *
- 신고기능에서 검색 기능 추가하였습니다.
* * *
- 컨트롤 로직입니다.
```
@ApiOperation(value = "신고관리 검색", notes = "신고자 검색", tags = {"ReportController"})
@GetMapping("/search")
public ResponseEntity<?> selectSearchReportList (
@RequestParam(name = "s", defaultValue = "all") String search) {
return ResponseEntity
.ok()
.body(new LoginMessage(HttpStatus.OK, "조회 성공", reportService.selectReportList(search)));
}
```
- 서비스 로직 입니다.
```
public List<Report> selectReportList(String search) {
log.info("[ReportService] selectReportList Start =================");
log.info("[ReportService] search : {}", search);
List<Report> reportListWithSearchValue = reportRepository.findByReportUserNickContaining(search);
log.info("[ReportService] selectReportList END ===================");
return …
```
> :memo: [BE][FEATURE]신고기능 Search 기능 추가

- src/main/java/com/mergeco/oiljang/message/controller/MsgController.java
- src/main/java/com/mergeco/oiljang/message/dto/MsgListDTO.java
- src/main/java/com/mergeco/oiljang/message/service/MsgService.java
* * *
- #48 
* * *
* * *
- 쪽지 리스트 dto 필드 바꿨습니다
* * *
- 쪽지 리스트 dto 필드 바꿨습니다
- 
* * *
* * *
* * *
> [BE][FEATURE]쪽지 리스트 조회 DTO수정

- src/main/java/com/mergeco/oiljang/product/controller/ProductController.java
- src/main/java/com/mergeco/oiljang/product/service/ProductService.java
- src/test/java/com/mergeco/oiljang/product/controller/ProductControllerTests.java
* * *
- #57 
* * *
* * *
- 관심 목록 제대로 조회 안 되던 거 수정했습니다.
* * *
- productController에서 @RequestBody로 DTO 받아오도록 했고, 로직도 w.refUserCode = :refProductCode로 바꿨습니다.
* * *
* * *
* * *
product 관련 문제가 생긴다면 말씀해주세요.
> 20231122-product-001 관심 목록 찜 제대로 안 되는 거 수정했습니다.

- src/main/java/com/mergeco/oiljang/auth/config/JwtSecurityConfig.java
- src/main/java/com/mergeco/oiljang/auth/config/OAuth2Config.java
- src/main/java/com/mergeco/oiljang/auth/config/WebSecurityConfig.java
- src/main/java/com/mergeco/oiljang/auth/filter/CustomAuthenticationFilter.java
- src/main/java/com/mergeco/oiljang/auth/handler/OAuth2SuccessHandler.java
- src/main/java/com/mergeco/oiljang/auth/model/DetailsUser.java
- src/main/java/com/mergeco/oiljang/auth/model/service/OAuth2DetailsService.java
- src/main/java/com/mergeco/oiljang/user/controller/OAuth2Controller.java
- src/main/java/com/mergeco/oiljang/user/model/service/OAuth2Service.java
- src/main/java/com/mergeco/oiljang/user/model/service/UserService.java
- src/main/java/com/mergeco/oiljang/user/repository/UserRepository.java
- src/main/resources/application.yml
* * *
- #5 
* * *
* * *
- 구글 로그인 기능 구현
* * *
- 구글 로그인 관련된 파일 추가 및 수정
* * *
- 현재 회원가입,로그인이 가능하지만 바로 회원가입이 되면서 바로 로그인이 되는 현상 발생
- 컨트롤러를 만들었지만 시큐리티에서 설정한 내용으로 인해 컨트롤러를 사용하지 않음.
- 리다이렉트 url이 메인페이지가 아닌 http://localhost:8000/oauth2/login/google/callback으로 이동하는 현상 발생.
* * *
- 회원 가입 및 로그인 성공
* * *
- 구글 로그인은 가능하지만 쿠키에 저장하지 않는 부분 체크 중입니다.
> [BE][Feature] 로그인

- src/main/java/com/mergeco/oiljang/message/controller/MsgController.java
- src/main/java/com/mergeco/oiljang/message/dto/MsgProUserInfoDTO.java
- src/main/java/com/mergeco/oiljang/message/service/MsgService.java
- src/test/java/com/mergeco/oiljang/message/MessageTests.java
* * *
* * *
* * *
- 쪽지 등록 관련 DTO 필드 수정했습니다. 
* * *
- 리액트에서 쪽지 등록을 할 때, refProductCode가 undefined로 값을 받아오는 문제가 있었는데, 관련 dto의 필드에서 product코드만 정의했고 refProduct코드는 정의하지 않았기 때문이었습니다. 해당 필드 추가해주었습니다.
* * *
* * *
* * *
> [BE][BUG]쪽지 등록 관련 DTO 필드 수정

- src/main/java/com/mergeco/oiljang/report/controller/ReportController.java
* * *
-
* * *
* * *
- 페이징 처리 작업중입니다.
* * *
- ![image](https://github.com/Merge-co/OIL-JANG_BE/assets/137472733/2ff53d6e-7d87-4ae1-babb-e2e70fc08c37)
- 페이징 처리를 위한 컴포넌트에 DTO 생성하였습니다 
* * *
* * *
- 현재 소스 작성중입니다.
* * *
> :technologist: [BE][FEATURE]신고기능 페이징 처리

- src/main/java/com/mergeco/oiljang/product/service/ProductService.java
* * *
- #6 
* * *
* * *
- 상품등록 완료 했습니당.
* * *
- 사용자마다 경로가 다 다르기 때문에 경로 수정 했습니다.
* * *
- ``
Product product = productRepository.findById(productCode).orElseThrow(null);
String ostype = "C:/images/";
String thumbName = UUID.randomUUID().toString();
String ext = imageFiles.get(0).getOriginalFilename().substring(imageFiles.get(0).getOriginalFilename().lastIndexOf("."));
if (System.getProperty("os.name").indexOf("Windows") != -1 ){
ostype = "C:/images/";
} else if (System.getProperty("os.name").indexOf("Mac") != -1) {
ostype = "/Users/minbumkim/Desktop/test/";
}
File thumbnailFile = new File(ostype + thumbName + ext);
BufferedImage img = ImageIO.read(imageFiles.get(0).getInputStream());
Thumbnails.of(imageFiles.get(0).getInputStream()).size(219,166).toFile(thumbnailFile);
product = …
> [BE][BUG] 상품등록 완료

- src/main/java/com/mergeco/oiljang/report/controller/ReportController.java
- src/main/java/com/mergeco/oiljang/report/repository/ReportRepository.java
- src/main/java/com/mergeco/oiljang/report/service/ReportService.java
* * *
- #101 
* * *
* * *
- 신고관리 페이지 페이징 처리 하였습니다
* * *
- 기존 GETMapping 에서 페이징 처리 위한 추가 로직 처리 하였습니다 
- 컨트롤러 로직입니다.
```
@ApiOperation(value = "신고관리", notes = "신고관리 페이지입니다.", tags = {"ReportController"})
@GetMapping("/reports")
public ResponseEntity<?> selectReportListWithPageing(
@RequestParam(name = "offset", defaultValue = "1") String offset) {
log.info("[ReportController] selectReportListWithPaging Start ====");
log.info("[ReportController] selectReportListWithPaging offset : {} ", offset);
int total = reportService.selectProejctTotal();
Criteria cri = new Criteria(Integer.valueOf(offset), 10);
PagingResponseDTO pagingResponseDTO = new PagingResponseDTO();
//         1. offset의 번호에 맞는 페이지에 뿌려줄 Report
pagingResponseDTO.setData(reportService.selectReportListWithPaging(cri));
//         2. …
```
> :monocle_face: [BE][FEATURE] 신고기능 페이징처리 구현

- src/main/java/com/mergeco/oiljang/message/controller/MsgController.java
- src/main/java/com/mergeco/oiljang/message/entity/MsgDeleteInfo.java
- src/main/java/com/mergeco/oiljang/message/service/MsgService.java
- src/test/java/com/mergeco/oiljang/message/MessageTests.java
* * *
* * *
* * *
- 설명을 작성하세요.
- 설명을 작성하세요.
* * *
- 변경 사항을 작성하세요.
- 변경 사항을 작성하세요.
* * *
- 오류 사항을 작성하세요.
- 오류 사항을 작성하세요.
* * *
* * *
> 20231124 msg 03

- src/main/java/com/mergeco/oiljang/message/controller/MsgController.java
- src/main/java/com/mergeco/oiljang/message/entity/MsgDeleteInfo.java
- src/main/java/com/mergeco/oiljang/message/service/MsgService.java
- src/test/java/com/mergeco/oiljang/message/MessageTests.java
* * *
* * *
* * *
- 설명을 작성하세요.
- 설명을 작성하세요.
* * *
- 변경 사항을 작성하세요.
- 변경 사항을 작성하세요.
* * *
- 오류 사항을 작성하세요.
- 오류 사항을 작성하세요.
* * *
* * *
> 20231124 msg 02

- src/main/java/com/mergeco/oiljang/auth/filter/CustomAuthenticationFilter.java
- src/main/java/com/mergeco/oiljang/auth/handler/OAuth2SuccessHandler.java
* * *
- #5 
* * *
* * *
- 구글 로그인 기능 오류 수정
* * *
- 구글 로그인 관련된 successhandler 수정
* * *
- 도메인 및 포트번호가 달라서 cors 이슈가 있습니다.
- 해당 부분 해소하기 위해 successhandler에 html 내용을 응답내용에 보냈습니다. 
* * *
- 구글 로그인 완료
* * *
- 현재 소셜 로그인은 구글만 진행하고 있으므로 테스트 시 구글 계정이 필요합니다.
- 구글 계정을 테스트 시 테스터에 등록이 필요하므로 테스트를 원하시면 구글 이메일을 보내주시기 바랍니다.
> [BE][Feature] 로그인 수정

- src/main/java/com/mergeco/oiljang/product/entity/Product.java
- src/main/java/com/mergeco/oiljang/product/service/ProductService.java
* * *
- #60 
* * *
* * *
- 설명을 작성하세요.
- 설명을 작성하세요.
* * *
- ProductService 수정했습니다
* * *
- ``        const updatedFields = {
price: parseFloat(price) || 0, // price가 NaN이면 0으로 설정
productDesc: productDesc || '', // productDesc가 undefined이면 빈 문자열로 설정
productName: productName || '', // productName이 undefined이면 빈 문자열로 설정
refCategoryCode: refCategoryCode || '', // refCategoryCode가 undefined이면 빈 문자열로 설정
wishPlaceTrade: wishPlaceTrade || '',
};
console.log('Product Code:', params.productCode);
console.log('Updated Fields:', updatedFields);
try {
await callProductEditAPI(params.productCode, updatedFields);
console.log('Received productCode:', productCode);
console.log('Received updatedFields:', updatedFields);
console.log('상품 수정 완료');
alert('상품 수정이 완료되었습니다. 메인페이지로 이동합니다.')
navigate('/');
} catch …
> [BE][BUG]상품삭제 완료

- src/main/java/com/mergeco/oiljang/report/controller/ReportController.java
- src/main/java/com/mergeco/oiljang/report/repository/ReportRepository.java
- src/main/java/com/mergeco/oiljang/report/service/ReportService.java
- src/test/java/com/mergeco/oiljang/report/ReportTests.java
* * *
- #90 
* * *
* * *
- 기존에는 처리 미처리 따로 검색 따로 API요청을 하였습니다.
현재 수정된것은 페이징 처리 전체 조회 처리 미처리 검색 기능 한번에 묶어서 진행하였씁니다.
하기의 로직 확인바랍니다.
* * *
```
@ApiOperation(value = "신고관리", notes = "신고관리 페이지입니다.", tags = {"ReportController"})
@GetMapping("/reports")
public ResponseEntity<?> selectReportListWithPageing(
@RequestParam(name = "offset", defaultValue = "1") String offset,
@RequestParam(name = "s", defaultValue = "all") String search,
@RequestParam(name = "p", defaultValue = "all") String processed) {
log.info("[ReportController] selectReportListWithPagingAndSearch Start ========");
log.info("[ReportController] selectReportListWithPagingAndSearch offset : {}", offset);
log.info("[ReportController] selectReportListWithPagingAndSearch search : {}", search);
log.info("[ReportController] …
```
> 🔹 [BE][FEATURE]신고기능 처리,미처리,검색 기능 수정

- src/main/java/com/mergeco/oiljang/message/controller/MsgController.java
- src/main/java/com/mergeco/oiljang/message/repository/MsgDeleteRepository.java
- src/main/java/com/mergeco/oiljang/message/service/MsgService.java
- src/test/java/com/mergeco/oiljang/message/MessageTests.java
* * *
- #48 
* * *
* * *
- 쪽지 조회에 검색기능을 하나의 URL로 합쳤습니다.
* * *
@ApiOperation(value = "쪽지 리스트 조회")
@GetMapping("/users/{userCode}/messages")
public ResponseEntity<ResponseMessage> getMessages(
@RequestParam(required = false) Integer page,
@PathVariable int userCode,
@RequestParam Boolean isReceived,
@RequestParam(required = false) String keyword) {
if(page == null){
page = 1;
}
HttpHeaders headers = new HttpHeaders();
headers.setContentType(new MediaType("application", "json", Charset.forName("UTF-8")));
int limit = 10;
int offset = limit * (page - 1);
List<MsgListDTO> msgList = msgService.getMessages(userCode, page, offset, limit, isReceived, keyword);
Map<String, Object> responseMap = new HashMap<>();
responseMap.put("msgList", msgList);
double totalMsg = …
> [BE][FEATURE]쪽지 검색 기능 관련 컨트롤러 변경

- src/main/java/com/mergeco/oiljang/message/controller/MsgController.java
- src/main/java/com/mergeco/oiljang/message/dto/MsgReceiverDTO.java
- src/main/java/com/mergeco/oiljang/message/entity/Message.java
- src/main/java/com/mergeco/oiljang/message/service/MsgService.java
- src/main/java/com/mergeco/oiljang/product/dto/ProductDetailDTO.java
- src/main/java/com/mergeco/oiljang/product/service/ProductService.java
- src/test/java/com/mergeco/oiljang/message/MessageTests.java
* * *
* * *
* * *
- 쪽지 조회 관련 쿼리문 수정했습니다
* * *
- 받은쪽지, 보낸쪽지 관련해서 혼동이 있었습니다
```
if (isReceived != null && isReceived) {
jpql = "SELECT new com.mergeco.oiljang.message.dto.MsgListDTO(u.userCode, u.name, u.id, m.msgCode, m.senderCode, m.receiverCode, m.msgContent, m.msgStatus, m.msgTime, md.msgDeleteCode) "
+ "FROM message_and_delete m "
+ "LEFT JOIN User u ON m.senderCode = u.userCode "
+ "JOIN m.msgDeleteInfo md "
+ "WHERE m.receiverCode = :userCode AND md.msgDeleteCode IN (1, 3) "
+ "AND (m.msgContent LIKE CONCAT('%', :keyword, '%') OR u.name LIKE CONCAT('%', :keyword, '%'))";
System.out.println("거치는지 확인");
} else {
jpql = "SELECT new com.mergeco.oiljang.message.dto.MsgListDTO(u.userCode, u.name, u.id, m.msgCode, m.senderCode, m.receiverCode, m.msgContent, …
```
> [BE][BUG]쪽지 조회 관련 쿼리문 수정

- src/main/java/com/mergeco/oiljang/product/service/ProductService.java
* * *
- #59 
* * *
* * *
- 상품수정 완료했습니다
* * *
- ``
// 새로운 정보로 업데이트
existingProduct.productName(updatedProductDTO.getProductName());
existingProduct.productPrice(updatedProductDTO.getProductPrice());
existingProduct.productDesc(updatedProductDTO.getProductDesc());
System.out.println(updatedProductDTO.getWishPlaceTrade());
existingProduct.wishPlaceTrade(updatedProductDTO.getWishPlaceTrade());
existingProduct.category(updatedProductDTO.getRefCategoryCode());
``
- 상품가격이 변경되지 않아 existingProduct.productPrice(updatedProductDTO.getProductPrice());를 추가 하였습니다.
* * *
> [BE][BUG]상품수정 완료

- src/main/java/com/mergeco/oiljang/myCalendar/controller/MyCalendarController.java
- src/main/java/com/mergeco/oiljang/myCalendar/dto/MyCalendarDTO.java
- src/main/java/com/mergeco/oiljang/myCalendar/entity/MyCalendar.java
- src/main/java/com/mergeco/oiljang/myCalendar/repository/MyCalendarRepository.java
- src/main/java/com/mergeco/oiljang/myCalendar/service/MyCalendarService.java
- src/main/java/com/mergeco/oiljang/product/controller/ProductController.java
- src/test/java/com/mergeco/oiljang/myCalendar/controller/MyCalendarControllerTests.java
- src/test/java/com/mergeco/oiljang/myCalendar/service/MyCalendarServiceTests.java
- src/test/java/com/mergeco/oiljang/product/controller/ProductControllerTests.java
* * *
* * *
* * *
MyCalendar 관련 도메인 추가 및 파일을 추가 했습니다. DB 테이블도 만들었습니다.
* * *
MyCalendar 관련 service, controller, repository, dto, entity 파일들을 추가했습니다.
* * *
* * *
* * *
> [BE][Feature] MyCalendar 관련 도메인 추가 및 파일 추가

- src/main/java/com/mergeco/oiljang/auth/config/WebSecurityConfig.java
- src/main/java/com/mergeco/oiljang/auth/filter/JwtFilter.java
- src/main/java/com/mergeco/oiljang/auth/model/service/DetailsService.java
- src/main/java/com/mergeco/oiljang/user/controller/UserController.java
- src/main/java/com/mergeco/oiljang/user/model/service/UserService.java
* * *
* * *
* * *
- 설명을 작성하세요.
- 설명을 작성하세요.
* * *
- 변경 사항을 작성하세요.
- 변경 사항을 작성하세요.
* * *
- 오류 사항을 작성하세요.
- 오류 사항을 작성하세요.
* * *
* * *
> [BE][Feature] 회원정보 수정

- src/main/java/com/mergeco/oiljang/inquiry/controller/InqController.java
- src/main/java/com/mergeco/oiljang/inquiry/dto/InqSelectListDTO.java
- src/main/java/com/mergeco/oiljang/inquiry/repository/InqCategoryRepository.java
- src/main/java/com/mergeco/oiljang/inquiry/service/InqService.java
- src/test/java/com/mergeco/oiljang/inquiry/InquiryTests.java
* * *
- #53 
* * *
* * *
- 1:1문의 겹치는 URL 수정했습니다
* * *
- keyword로 검색해서 조회하는 url을 조회 url로 하나로 합쳤습니다
```
@ApiOperation(value = "문의 리스트 조회")
@GetMapping("/users/{userCode}/inquiries")
public ResponseEntity<ResponseMessage> inqSelectList(
@RequestParam(required = false) Integer page,
@PathVariable int userCode,
@RequestParam UserRole role,
@RequestParam(required = false) String keyword
){
if(page == null){
page = 1;
}
HttpHeaders headers = new HttpHeaders();
headers.setContentType(new MediaType("application", "json", Charset.forName("UTF-8")));
int limit = 10;
int offset = limit * (page - 1);
List<InqSelectListDTO> inqSelectListDTOList = inqService.selectInqList(page, userCode, role, offset, limit, keyword);
Map<String, Object> responseMap = new HashMap<>(); …
```
> [BE][BUG]1:1문의 겹치는 URL 수정

- src/main/java/com/mergeco/oiljang/auth/config/OAuth2Config.java
- src/main/java/com/mergeco/oiljang/auth/config/WebSecurityConfig.java
- src/main/java/com/mergeco/oiljang/auth/handler/OAuth2SuccessHandler.java
- src/main/java/com/mergeco/oiljang/user/controller/UserController.java
- src/main/java/com/mergeco/oiljang/user/model/dto/UpdateUserDTO.java
- src/main/java/com/mergeco/oiljang/user/model/dto/UserDTO.java
- src/main/java/com/mergeco/oiljang/user/model/service/OAuth2Service.java
- src/main/java/com/mergeco/oiljang/user/model/service/UserService.java
- src/main/java/com/mergeco/oiljang/user/repository/UserRepository.java
- src/main/resources/application.yml
* * *
- #66 
- #5 
- #68 
* * *
* * *
- 네이버 로그인 추가
- 비밀번호 변경 추가
- 아이디 찾기 추가
* * *
- 네이버 로그인 기능으로 인한 시큐리티 및 관련 컨트롤러 수정
- 비밀번호만 변경 기능으로 인한 컨트롤러,서비스,레포지토리 추가
- 아이디 찾기 기능으로 인한 컨트롤러,서비스,레포지토리 추가
* * *
- 없음.
* * *
- 진행 중
* * *
- 없습니다.
> [BE][Feature] 회원 기능 수정

- src/main/java/com/mergeco/oiljang/myCalendar/dto/MyCalendarDTO.java
- src/main/java/com/mergeco/oiljang/myCalendar/entity/MyCalendar.java
- src/main/java/com/mergeco/oiljang/myCalendar/service/MyCalendarService.java
- src/test/java/com/mergeco/oiljang/myCalendar/controller/MyCalendarControllerTests.java
- src/test/java/com/mergeco/oiljang/myCalendar/service/MyCalendarServiceTests.java
* * *
- #116 
* * *
* * *
캘린더에서 시간을 등록할 수 있도록 관련 파일을 수정했습니다. 
* * *
* * *
* * *
* * *
> [BE][Feature] 

- src/main/java/com/mergeco/oiljang/myCalendar/service/MyCalendarService.java
- src/main/java/com/mergeco/oiljang/product/service/ProductService.java
* * *
* * *
* * *
캘린더 탭 2개 틀 상황을 대비해서 수정 두번 해도 문제가 없도록 했습니다.
* * *
```
@Transactional
public String updateMyCalendar(int myCalendarCode, MyCalendarDTO myCalendarDTO) {
String result = "캘린더에 내용 수정 실패";
MyCalendar myCalendar = myCalendarRepository.findById(myCalendarCode).orElse(null);
if(myCalendar != null) {
myCalendar = myCalendar = myCalendar.calendarContent(myCalendarDTO.getCalendarContent())
.calendarDate(myCalendarDTO.getCalendarDate()).calendarTime(myCalendarDTO.getCalendarTime()).builder();
result = "캘린더에 내용 수정 성공";
}
return result;
}
```
* * *
* * *
* * *
> [BE][Feature] 캘린더 수정 시 생길 수 있는 버그 수정

- src/main/java/com/mergeco/oiljang/inquiry/controller/InqController.java
- src/main/java/com/mergeco/oiljang/inquiry/service/InqService.java
- src/main/java/com/mergeco/oiljang/message/controller/MsgController.java
- src/main/java/com/mergeco/oiljang/message/service/MsgService.java
* * *
- #53 
* * *
* * *
- 관리자일 경우 전체 조회
```
if ("ROLE_ADMIN".equals(role) && role != null & role != "") {
jpql = "SELECT new com.mergeco.oiljang.inquiry.dto.InqSelectListDTO(i.inqCode, i.refUserCode, u.userCode, u.name, u.id, u.role, i.inqTitle, i.inqTime, i.inqStatus, c.inqCateCode, c.inqCateName) "
+ "FROM inquiry_and_category i "
+ "LEFT JOIN User u ON i.refUserCode = u.userCode "
+ "JOIN i.inqCategory c "
+ "WHERE i.refUserCode != :userCode ";
```
- 유저일 경우 전체 조회
```
else {
System.out.println(" 거쳐가는지?================================================");
jpql = "SELECT new com.mergeco.oiljang.inquiry.dto.InqSelectListDTO(i.inqCode, i.refUserCode, u.userCode, u.name, u.id, u.role, i.inqTitle, i.inqTime, i.inqStatus, c.inqCateCode, c.inqCateName) "
+ "FROM inquiry_and_category i "
+ "LEFT …
```
> [BE][BUG]1:1문의 조건 조회 쿼리문 수정

- src/main/java/com/mergeco/oiljang/product/service/ProductService.java
* * *
- #61 
* * *
* * *
- 내 판매목록 전체갯수 수정 및 페이징 오류 처리 했습니다.
* * *
- ProductService 수정했습니다.
* * *
``
public Long countSellingList(int refUserCode) {
String jpql = "select count (*) from Product p WHERE p.refUserCode = :refUserCode and p.SellStatus.sellStatusCode in(1, 2) ORDER BY p.productCode DESC";
Long countPage = (Long) entityManager.createQuery(jpql)
.setParameter("refUserCode", refUserCode)
.getSingleResult();
return countPage;
}
``
* * *
-
> [BE][BUG]내 판매목록 전체갯수 수정

- src/main/java/com/mergeco/oiljang/auth/config/WebSecurityConfig.java
- src/main/java/com/mergeco/oiljang/auth/handler/CustomAuthSuccessHandler.java
- src/main/java/com/mergeco/oiljang/userSanctions/repository/UserSanctionsRepository.java
- src/main/java/com/mergeco/oiljang/userSanctions/service/SanctionsService.java
* * *
- #125 
- #5 
* * *
* * *
- 제재 회원 로그인 제한 기능
* * *
- 아이디 비밀번호 검증 후 제재 회원인지 체크하는 로직 추가
* * *
- 현재 한 회원이 중복으로 등록되어있으면 오류 발생합니다.
* * *
- 없음.
* * *
- 없음.
> [BE][Feature] 제재 회원 로그인 제한 기능 추가

- src/main/java/com/mergeco/oiljang/inquiry/service/InqService.java
- src/main/java/com/mergeco/oiljang/message/service/MsgService.java
* * *
- #48 
* * *
* * *
- 쪽지 키워드 조회 관련 서비스로직 수정했습니다
* * *
- 조건으로 keyword 가 있을 때 jpql로 뒤에 조건절을 덧붙였습니다
``` 
if(keyword != null && keyword != ""){
jpql += "AND m.msgContent LIKE :keyword OR u.name LIKE :keyword ORDER BY m.msgTime DESC ";
```
* * *
* * *
* * *
> [BE][BUG]쪽지 키워드 조회 관련 서비스로직 수정

- src/main/java/com/mergeco/oiljang/product/controller/ProductController.java
- src/main/java/com/mergeco/oiljang/product/service/ProductService.java
* * *
- #61 
* * *
* * *
- 상품상태 변경 오류 수정했습니다
* * *
- ProductService&ProductController 변경했습니다!
* * *
``
public List<SellingListDTO> selectSellingList(int offset, int limit, int refUserCode) {
String jpql = "SELECT new com.mergeco.oiljang.product.dto.SellingListDTO(p.productCode, p.productThumbAddr, p.productName, p.productPrice,(SELECT Count(w.wishCode) FROM WishList w WHERE w.product.productCode = p.productCode), (SELECT s.sellStatus from SellStatus s WHERE s.sellStatusCode = p.SellStatus.sellStatusCode))" +
" FROM Product p WHERE p.refUserCode = :refUserCode and p.SellStatus.sellStatusCode in(1, 2) ORDER BY p.productCode DESC";
List<SellingListDTO> wishList = entityManager.createQuery(jpql)
.setParameter("refUserCode", refUserCode)
.setFirstResult(offset)
.setMaxResults(limit) …
> [BE][BUG]상품상태변경 오류 수정

- src/main/java/com/mergeco/oiljang/product/dto/SellingListDTO.java
* * *
- #61 
* * *
* * *
- 설명을 작성하세요.
- 설명을 작성하세요.
* * *
- 변경 사항을 작성하세요.
- 변경 사항을 작성하세요.
* * *
- 오류 사항을 작성하세요.
- 오류 사항을 작성하세요.
* * *
* * *
> [BE][BUG]내 판매목록 상태변경 오류 완료
